spin_manifest_version = 2

[application]
authors = ["tanishiking <rikiriki1238@gmail.com>"]
description = ""
name = "spin-scalajs-example"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "scalajs-spin"

[component.spin-scalajs-example]
source = "target/main.wasm"
exclude_files = ["**/node_modules"]

[component.spin-scalajs-example.build]
command = "sbtn buildWasm"
